### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nikivazou** [plum-umd/lmonad-meta#5]
- [ ] There is an indexing are equal admit https://github.com/plum-umd/lmonad-meta/blob/6808fbe7ed5a5039111660a95ca542168a58aaa6/src/src/Simulations.hs#L20

- [ ] There is a lazy annotation https://github.com/plum-umd/lmonad-meta/blob/d7a2ddfd714aa131bddaad9418e471a39b979c71/src/src/Programs.hs#L88

- [ ] Remove this unreachable branch: https://github.com/plum-umd/lmonad-meta/blob/d7a2ddfd714aa131bddaad9418e471a39b979c71/src/src/Simulations.hs#L88 by turning `ς` into a measure.
